# Port 8883 - MQTT przez TLS (API <-> Broker) - ZOSTAJE TAK SAMO
listener 8883
protocol mqtt
certfile /home/jakub/UG/2025_zimowy/PROJEKT_PSW/src/certs/server.crt
keyfile /home/jakub/UG/2025_zimowy/PROJEKT_PSW/src/certs/server.key

# Port 9001 - WebSockets bez TLS (Przeglądarka <-> Broker) - ZMIANA
listener 9001
protocol websockets
# certfile i keyfile usunięte lub zakomentowane

allow_anonymous true
